create extension if not exists pgcrypto;
create table if not exists public.site_settings(key text primary key,value text not null default '');
create table if not exists public.team_members(id uuid primary key default gen_random_uuid(),name text not null,role text default 'Professional Team Member',bio text default '',photo_url text default '',gender_group text default '',created_at timestamptz default now());
create table if not exists public.services(id uuid primary key default gen_random_uuid(),name text unique not null,description text default '',page_url text default '',image_url text default '',created_at timestamptz default now());
create table if not exists public.insurance_plans(id uuid primary key default gen_random_uuid(),name text unique not null,suitable_for text default '',main_point text default '',sort_order int default 0);
create table if not exists public.leads(id uuid primary key default gen_random_uuid(),name text,zip_code text,age int,state text,coverage_type text,phone text,email text,message text,source_page text,created_at timestamptz default now());
create table if not exists public.consultations(id uuid primary key default gen_random_uuid(),name text,phone text,email text,method text,preferred_date date,preferred_time time,message text,source_page text,created_at timestamptz default now());
insert into public.site_settings(key,value) values ("brand_name","Olivia Health Insurance") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("professional_name","Olivia") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("designation","Advocate & Legal Consultant") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("phone","+92 326 9048872") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("whatsapp","+92 326 9048872") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("email","salahudinayyubi099@gmail.com") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("address","New York City, USA") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("hours","Monday\u2013Saturday | 8:00 AM\u20136:00 PM") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("facebook","#") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("linkedin","#") on conflict(key) do update set value=excluded.value;
insert into public.site_settings(key,value) values ("instagram","#") on conflict(key) do update set value=excluded.value;
insert into public.services(name,description,page_url,image_url) values ("Individual Health Insurance","Flexible coverage options for individual healthcare needs.","individual-insurance.html","https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=85") on conflict(name) do update set description=excluded.description,page_url=excluded.page_url,image_url=excluded.image_url;
insert into public.services(name,description,page_url,image_url) values ("Family Health Insurance","Coverage options for families and dependents.","family-insurance.html","https://images.unsplash.com/photo-1609220136736-443140cffec6?auto=format&fit=crop&w=1200&q=85") on conflict(name) do update set description=excluded.description,page_url=excluded.page_url,image_url=excluded.image_url;
insert into public.services(name,description,page_url,image_url) values ("Medicare Plans","Understand Medicare-related options and eligibility considerations.","medicare.html","https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1200&q=85") on conflict(name) do update set description=excluded.description,page_url=excluded.page_url,image_url=excluded.image_url;
insert into public.services(name,description,page_url,image_url) values ("Medicaid Assistance","Learn about Medicaid eligibility and possible low-cost coverage.","medicaid.html","https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1200&q=85") on conflict(name) do update set description=excluded.description,page_url=excluded.page_url,image_url=excluded.image_url;
insert into public.services(name,description,page_url,image_url) values ("Dental & Vision Insurance","Explore supplemental dental and vision coverage.","dental-vision.html","https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1200&q=85") on conflict(name) do update set description=excluded.description,page_url=excluded.page_url,image_url=excluded.image_url;
insert into public.services(name,description,page_url,image_url) values ("Prescription Coverage","Understand prescription-drug coverage considerations.","prescription-coverage.html","https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=85") on conflict(name) do update set description=excluded.description,page_url=excluded.page_url,image_url=excluded.image_url;
insert into public.services(name,description,page_url,image_url) values ("Employer Health Plans","Explore health-benefit considerations for employers and teams.","employer-plans.html","https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=85") on conflict(name) do update set description=excluded.description,page_url=excluded.page_url,image_url=excluded.image_url;
insert into public.insurance_plans(name,suitable_for,main_point,sort_order) values ("Bronze","People who use healthcare less often","Lower premium, but generally higher costs when receiving care.",1) on conflict(name) do update set suitable_for=excluded.suitable_for,main_point=excluded.main_point,sort_order=excluded.sort_order;
insert into public.insurance_plans(name,suitable_for,main_point,sort_order) values ("Silver","People seeking a middle option","Moderate premium and out-of-pocket costs; extra savings may apply based on income.",2) on conflict(name) do update set suitable_for=excluded.suitable_for,main_point=excluded.main_point,sort_order=excluded.sort_order;
insert into public.insurance_plans(name,suitable_for,main_point,sort_order) values ("Gold","People expecting more medical care","Higher premium, but generally lower costs when receiving care.",3) on conflict(name) do update set suitable_for=excluded.suitable_for,main_point=excluded.main_point,sort_order=excluded.sort_order;
insert into public.insurance_plans(name,suitable_for,main_point,sort_order) values ("Platinum","People with frequent medical needs","Higher premium, but generally lower costs when receiving care.",4) on conflict(name) do update set suitable_for=excluded.suitable_for,main_point=excluded.main_point,sort_order=excluded.sort_order;
insert into public.team_members(name,role,gender_group,photo_url) values ("Emma",'Professional Team Member','Women',"assets/images/team-woman-1.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Sophia",'Professional Team Member','Women',"assets/images/team-woman-2.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Ava",'Professional Team Member','Women',"assets/images/team-woman-3.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Isabella",'Professional Team Member','Women',"assets/images/team-woman-4.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Mia",'Professional Team Member','Women',"assets/images/team-woman-5.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Charlotte",'Professional Team Member','Women',"assets/images/team-woman-6.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Amelia",'Professional Team Member','Women',"assets/images/team-woman-7.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Harper",'Professional Team Member','Women',"assets/images/team-woman-8.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Evelyn",'Professional Team Member','Women',"assets/images/team-woman-9.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Abigail",'Professional Team Member','Women',"assets/images/team-woman-10.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Emily",'Professional Team Member','Women',"assets/images/team-woman-11.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Ella",'Professional Team Member','Women',"assets/images/team-woman-12.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Madison",'Professional Team Member','Women',"assets/images/team-woman-13.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Lily",'Professional Team Member','Women',"assets/images/team-woman-14.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Liam",'Professional Team Member','Men',"assets/images/team-man-1.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Noah",'Professional Team Member','Men',"assets/images/team-man-2.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Oliver",'Professional Team Member','Men',"assets/images/team-man-3.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("James",'Professional Team Member','Men',"assets/images/team-man-4.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("William",'Professional Team Member','Men',"assets/images/team-man-5.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Benjamin",'Professional Team Member','Men',"assets/images/team-man-6.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Lucas",'Professional Team Member','Men',"assets/images/team-man-7.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Henry",'Professional Team Member','Men',"assets/images/team-man-8.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Theodore",'Professional Team Member','Men',"assets/images/team-man-9.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Jack",'Professional Team Member','Men',"assets/images/team-man-10.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Michael",'Professional Team Member','Men',"assets/images/team-man-11.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Daniel",'Professional Team Member','Men',"assets/images/team-man-12.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Alexander",'Professional Team Member','Men',"assets/images/team-man-13.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Mason",'Professional Team Member','Men',"assets/images/team-man-14.jpg");
insert into public.team_members(name,role,gender_group,photo_url) values ("Ethan",'Professional Team Member','Men',"assets/images/team-man-15.jpg");
alter table public.site_settings enable row level security;
alter table public.team_members enable row level security;
alter table public.services enable row level security;
alter table public.insurance_plans enable row level security;
alter table public.leads enable row level security;
alter table public.consultations enable row level security;
create policy "public read settings" on public.site_settings for select using(true);
create policy "public read team" on public.team_members for select using(true);
create policy "public read services" on public.services for select using(true);
create policy "public read plans" on public.insurance_plans for select using(true);
create policy "public insert leads" on public.leads for insert with check(true);
create policy "public insert consultations" on public.consultations for insert with check(true);
create policy "auth read leads" on public.leads for select to authenticated using(true);
create policy "auth read consultations" on public.consultations for select to authenticated using(true);
create policy "auth manage settings" on public.site_settings for all to authenticated using(true) with check(true);
create policy "auth manage team" on public.team_members for all to authenticated using(true) with check(true);
create policy "auth manage services" on public.services for all to authenticated using(true) with check(true);
create policy "auth manage plans" on public.insurance_plans for all to authenticated using(true) with check(true);

-- Private admin media library. Uploads are accessible only to authenticated admin users.
insert into storage.buckets (id, name, public) values ('site-files','site-files',false) on conflict (id) do nothing;

drop policy if exists "Authenticated users can view site files" on storage.objects;
drop policy if exists "Authenticated users can upload site files" on storage.objects;
drop policy if exists "Authenticated users can update site files" on storage.objects;
drop policy if exists "Authenticated users can delete site files" on storage.objects;

create policy "Authenticated users can view site files" on storage.objects for select to authenticated using (bucket_id = 'site-files');
create policy "Authenticated users can upload site files" on storage.objects for insert to authenticated with check (bucket_id = 'site-files');
create policy "Authenticated users can update site files" on storage.objects for update to authenticated using (bucket_id = 'site-files') with check (bucket_id = 'site-files');
create policy "Authenticated users can delete site files" on storage.objects for delete to authenticated using (bucket_id = 'site-files');
